### ISSUE TITLE
Notifications don't get triggered in tmux session

### ISSUE THREAD

**Issue by variadico** [variadico/noti#1]
This is an issue that also occurs in other utils like `st` or `pbcopy`. I'm not sure if there is anything I can do to fix it, but here is a workaround.

https://github.com/ChrisJohnsen/tmux-MacOSX-pasteboard

**Comment by mgbellaire** [comment]
Having the workaround above helps a lot! Thanks for sharing that in the meantime.

**Comment by variadico** [comment]
Noti has magically started working in tmux on macOS!

Go: 1.9.2 darwin/amd64
macOS: 10.13.2
noti: 2.7.0
