### ISSUE TITLE
Signify success/failure of command in notification

### ISSUE THREAD

**Issue by golergka** [variadico/noti#10]
It would be useful if Noti could indicate if the last command has ended successfully (with exit code 0) or not.

**Comment by variadico** [comment]
We already have this.

If your command is successful, then the notification message is "done" (or whatever you set `-m` to). If it's not successful, then you get "exit status 1".

Were you thinking of something different?

**Comment by variadico** [comment]
The comment above applies to v2, which I've been running for a while. However, I checked v1.3.0 and it also shows success and failure.

**Success**
![image](https://cloud.githubusercontent.com/assets/4296393/12705747/4e8e6ce0-c82b-11e5-882d-a2f8c331e1a8.png)

**Failure**
![image](https://cloud.githubusercontent.com/assets/4296393/12705735/0ff6876a-c82b-11e5-99fa-06f4b68839b4.png)
