### ISSUE TITLE
Support for Keybase

### ISSUE THREAD

**Issue by pascalandy** [variadico/noti#103]
Here is why: https://keybase.io/blog/slack-incident

> Slack announced that a break-in from 2015 was possibly more severe than previously announced. A lot of people have been getting emails today. It seems 1% of Slack users still had compromised accounts (after 4 years); but more seriously, Slack has not disclosed what percent of Slack teams had their messages stolen. Also, if a small fraction of users have had compromised accounts, that may still mean a majority of teams were compromised.

> We're sending this note because people are now asking if this could happen with Keybase teams. Simple answer: no. While Keybase now has all the important features of Slack, it has the only protection against server break-ins: **end-to-end encryption**.

**Comment by variadico** [comment]
Sounds great. Can someone help with the implementation?

**Comment by dawidd6** [comment]
Relevant code: https://github.com/keybase/go-keybase-chat-bot

**Comment by variadico** [comment]
Fixed in https://github.com/variadico/noti/pull/113

**Comment by pascalandy** [comment]
You guys rock! I think it's time to switch my Chat/DevOps/Notifications to Keybase :)
