### ISSUE TITLE
Doc update: Install from source wrong path

### ISSUE THREAD

**Issue by pascalandy** [variadico/noti#107]
Hi,

I was messing around to install from sources. 

The missing part we should add in the README that you have to build from this path `https://github.com/variadico/noti/cmd/noti`

### README section:
https://github.com/variadico/noti/tree/3.2.0#from-source

If you agree, let me know I'll do a PR.

**Comment by variadico** [comment]
Did it not build for you? What steps did you take to get the build to fail?

**Comment by pascalandy** [comment]
See line https://github.com/firepress-org/noti-in-docker/blob/master/Dockerfile#L31

I have to go there, else building from `https://github.com/variadico/noti` does not work.

**Comment by pascalandy** [comment]
Also, from your CI
https://circleci.com/gh/variadico/noti/440#tests/containers/0

![Screen Shot 2019-09-01 at 1 36 56 AM](https://user-images.githubusercontent.com/6694151/64072230-1354f000-cc59-11e9-8920-c6cfdd03ca62.jpg)

It's very strange actually.

**Comment by variadico** [comment]
Yep. I was about to suggest looking at the makefile.
https://github.com/variadico/noti/blob/master/Makefile#L9-L14

There are no buildable files at the root of the repo, that's why you can't build from there. The main function is in `cmd/noti`. That's why you either have to

```
cd cmd/noti
go build
```
or
```
go build github.com/variadico/noti/cmd/noti
```

I'm guessing something like this should work.

```
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 GOFLAGS="-mod=vendor" && \
    go build -o /usr/local/bin/"${APP_NAME}" github.com/variadico/noti/cmd/noti
```

**Comment by pascalandy** [comment]
So in the README then:

> we should add in the README that you have to build from this path https://github.com/variadico/noti/cmd/noti

**Comment by variadico** [comment]
Ah, but you don't have to build from that path. You can build from either directory.

```
# building from root of repo
$ cd noti/
$ pwd
/home/jaime/go/src/github.com/variadico/noti
$ go build github.com/variadico/noti/cmd/noti
```
or
```
# building from cmd dir
$ cd noti/cmd/noti/
$ pwd
/home/jaime/go/src/github.com/variadico/noti/cmd/noti
$ go build
```

But yeah, you have to change the build command. I would recommend building from the root, since that's a more interesting place to work from.

**Comment by variadico** [comment]
Oh, wait. I can see maybe something confusing in the readme.

It should probably say this.

```
go build -mod=vendor github.com/variadico/noti/cmd/noti
# or
export GOFLAGS="-mod=vendor"
go build github.com/variadico/noti/cmd/noti
```

**Comment by variadico** [comment]
This seems done. I'm gonna close it for now.
