### ISSUE TITLE
How to remove the username 'noti' on the first line of the message?

### ISSUE THREAD

**Issue by pascalandy** [variadico/noti#108]
Your see how the first line is only noise here:

![image](https://user-images.githubusercontent.com/6694151/64065832-b7e71b80-cbe0-11e9-9c8a-691624085c45.png)

It looks like there is a default `username` set as noti. That should not be there IMHO.

![image](https://user-images.githubusercontent.com/6694151/64065844-e06f1580-cbe0-11e9-9066-7f5c8bc7f22e.png)

**version**: 3.2.0

### I run:

```
NOTI_MESSAGE="Can you hear me"
NOTI_SLACK_TOKEN="$SLACK_TOKEN_CRON"
NOTI_SLACK_CHANNEL="$SLACK_CHANNEL"

noti -k -m "$NOTI_MESSAGE"
```

**Comment by variadico** [comment]
One way to remove one of the `noti`s is to make the title blank. The text for Slack notifications comes from combining the notification title and message.

https://github.com/variadico/noti/blob/master/internal/command/cloud.go#L85

Buuut, that does seem annoying to have to do all the time. The default behavior should be only 1 noti.

Fixed:
https://github.com/variadico/noti/commit/0a56f36b352dd929dc6eaa043522432dcf0045c0

**Comment by pascalandy** [comment]
I'll be waiting for the new release :)
