### ISSUE TITLE
error during build: go: github.com/variadico/vbs@v0.0.0-20170818035803-5eb949d57a46: invalid version

### ISSUE THREAD

**Issue by pascalandy** [variadico/noti#109]
As my docker image is usually building normally on my CI, I guess something happened on github.com/variadico/vbs?

### logs

https://github.com/firepress-org/noti-in-docker/commit/1e0ec2748aab86b4223a2b8a88b07d4cdb35209d/checks#step:4:161

**Comment by variadico** [comment]
Can you try this:
```
RUN set -eux && CGO_ENABLED=0 GOOS=linux GOARCH=amd64 GOFLAGS="-mod=vendor" \
    go build -o /usr/local/bin/"${APP_NAME}"
```

I removed the `&&` at the end.
```diff
- GOFLAGS="-mod=vendor" && \
+ GOFLAGS="-mod=vendor" \
```

The vendor directory isn't being used. I think the `&&` is causing the two sides to be executed in different shells.

**Comment by pascalandy** [comment]
That fixed it.
Thank you so much for all your help :)
