### ISSUE TITLE
Telegram Bad Request: chat not found

### ISSUE THREAD

**Issue by sdaitzman** [variadico/noti#116]
I set up Telegram access as described in the [guide](https://github.com/variadico/noti/blob/0538ed50e6b9c46e698f1753e4d92634cedf8f58/docs/noti.md#telegram). Every time I run `noti -g` I get the following output:

```fish
$ noti -g
2019/12/18 16:07:19 Bad Request: chat not found
```

**Comment by sdaitzman** [comment]
Solved my own issue. The "Chat ID" is separate from your username, and is a Telegram API construct that must be identified separately.

**Comment by lainiwa** [comment]
Might be helpful to someone:

1. Create bot at [BotFather](https://telegram.me/botfather) as described in the [docs](https://github.com/variadico/noti/blob/master/docs/noti.md#telegram).
2. Write to your bot (at `t.me/<USERNAME_BOT>`) a message.
3. Go to `https://api.telegram.org/bot<TOKEN>/getUpdates?offset=0` and copy the numerical chat id of the message (123456789 or something).
4. Set token and `chatId` at the [config](https://github.com/variadico/noti/blob/master/docs/noti.md#examples) (but without the `@` sign).
