### ISSUE TITLE
Is it possible to use it with webpack?

### ISSUE THREAD

**Issue by vaklinzi** [variadico/noti#118]
Thanks for the great project!
I have a long running webpack build process and would like to use noti to notify me when it is ready. Is that possible?
I tried with: `noti npm run webpack` but it's not working.

**Comment by variadico** [comment]
Hi, what OS are you running? What happens when you run that command? As far as I know, there shouldn't be anything special about npm. Need some more details to debug.

**Comment by variadico** [comment]
Oooh, does the `npm run webpack` command never finish?
I noticed one of the screenshots says:
> webpack is watching the files...

`noti` knows when something is done when the process dies, but in this case I think your webpack process is still alive, watching files.

**Comment by vaklinzi** [comment]
@variadico that's true, that was the reason to ask whether it's possible somehow. It is not an issue with the noti library but I was curious whether I can use it for that. Thank you again!
