### ISSUE TITLE
Homebrew needs to be updated to install v2.0.0

### ISSUE THREAD

**Issue by KingKrimmson** [variadico/noti#16]
Was just browsing your repo again today and noticed the new v2.0.0 release! Looks great and excited to try. Couldn't install with homebrew (still using v1.3.0) so I updated the Formula and submitted a pull request, should be done shortly.

For the record, I had to increment the dev version to `v2.0.1-rc.1` to prevent a homebrew error. Aware this is not actually a version.

[Homebrew Pull Reqest for noti 2.0.0](https://github.com/Homebrew/homebrew/pull/48836)

**Comment by variadico** [comment]
Sweet! Thank you!! I've been meaning to do this, but I've been busy.

**Comment by KingKrimmson** [comment]
After playing with v2.0.0 for a bit, I was curious, how easy would it be to bring back the -s tag for sounds rather than speech? I like the speech option but it is much more beneficial to me to be able to specify the sound for a specific notification.

For example, I'm using noti to notify me when build/deployments are complete or have failed. It was nice being able to specify the "Hero" sound for the error notification so I could easily tell the difference.

**Comment by variadico** [comment]
Created a new issue for this because this has nothing to do with updating Homebrew. #17

**Comment by KingKrimmson** [comment]
The homebrew pull request has been merged. This issue can be closed.
