### ISSUE TITLE
Feture request: Pushover notifications

### ISSUE THREAD

**Issue by joselitojunior1** [variadico/noti#18]
[Pushover](http://pushover.net) is a notification service, similar to Pushbullet. The main feature is that Pushover virtually integrates anything to they api, so you can get your notifications in any devices or services.

I can send a PR with that feature by myself, if you like.

**Comment by variadico** [comment]
Sounds good to me! Your PR is welcomed! Branch off of [dev](https://github.com/variadico/noti/tree/dev).

**Comment by joselitojunior1** [comment]
:+1:

**Comment by variadico** [comment]
Done. It'll be part of the v2.1.0 release.
https://github.com/variadico/noti/blob/dev/CHANGELOG.md#added

Sorry, you took too long! :) Thanks anyway!
