### ISSUE TITLE
Can't use title when running scripts

### ISSUE THREAD

**Issue by KingKrimmson** [variadico/noti#22]
#### Description

When using a command like `noti -t "Test" ~/scripts/build.sh`, Title is overridden by script path (i.e. "/Users/Chris/scripts/build.sh" instead of "Test") for success _and_ failure.

#### Use case

Would be great to be able to specify title as I use a system property $DSNAME to signify which project is done/failed building, deploying, etc.

#### Version

go v1.6
noti v2.1.0

**Comment by variadico** [comment]
Dang it! You found a bug! Thanks for reporting! Definitely gonna fix this! :smile:

**Comment by variadico** [comment]
Fixed!
https://github.com/variadico/noti/commit/bc2fb74e1c847604cfa134c7d84cd23722d9f9bc

Will try to push out a new release by this weekend.
