### ISSUE TITLE
Exit 1 not resulting in noti failure message.

### ISSUE THREAD

**Issue by KingKrimmson** [variadico/noti#25]
#### Description
When running noti with `noti -t $PSNAME -m "Script success" ~/scripts/script.sh`, I know the script is ending with `exit 1` or `die "foo"` but noti always processes this as a success and displays the success notification. 

This may just be a personal misunderstanding of how noti/go processes errors.

#### Use case
When a command returns with exit code 1.

#### Steps to reproduce
Create `script.sh`:
``` shell
#!/bin/bash
exit 1
```
Run with command `noti -t "Test" -m "Test" script.sh`

#### Expected behavior
Noti displays a notification with the exit message and plays the NOTI_SOUND_FAIL sound

#### Actual behavior
Noti displays a notification with the "Test" message and plays the NOTI_SOUND sound

#### Version
`noti v2.1.1`
`go v1.6`

**Comment by variadico** [comment]
Here's the break down of the behavior I observed.

```
noti fail.sh
  script.sh failed
  exit status 1

noti -t "test" fail.sh
  test
  exit status 1

noti -t "test" -m "test" fail.sh
  test
  test
```

Anytime you specify `-t` or `-m`, that takes precedence over everything. If you don't specify those flags, then `noti` tries to set some sort of sane value. I think that's the right behavior.

However, `NOTI_SOUND_FAIL` _should_ play in these cases. In fact, `NOTI_SOUND_FAIL` _did_ play for each of the above cases for me. What does `env | grep "NOTI"` look like? Is `NOTI_SOUND_FAIL` set to something?

**Comment by KingKrimmson** [comment]
Oops >.< Looks like my NOTI_SOUND_FAIL had a typo and was therefore reverting to default (which happens to be my NOTI_SOUND choice).

I guess two follow up requests then (didn't open up separate issues yet):

1. I pretty much always would like -t to override the "fail.sh failed" title, but wouldn't mind if error message took precedence over -m or if there was an option to designate this.

2. Would it be possible/easy to allow for the use of Custom sound effects if they are proprely configured in the OS? Even if this means I need to modify my local noti instance. Like:
![screen shot 2016-03-04 at 10 07 30 am](https://cloud.githubusercontent.com/assets/7947742/13530755/fac32e04-e1f0-11e5-9e77-caf5369dd1f5.png)

**Comment by variadico** [comment]
> Would it be possible/easy to allow for the use of Custom sound effects…

Not easy because Apple doesn't allow you to modify `/System/Library/Sounds` anymore.
https://support.apple.com/en-us/HT204899
