### ISSUE TITLE
Unable to set Pushover token

### ISSUE THREAD

**Issue by KingKrimmson** [variadico/noti#26]
#### Description
When attempting to use pushover option (`-o`), error message saying:
`Missing access token, NOTI_PUSHOVER_TOK must be set`
Even though system variable is definitely set.
Code which results in this error seems fine, just pulls this system variable. I have triple checked with `echo $NOTI_PUSHOVER_TOK` that this variable (and the other pushover token) are defined.

#### Use case
`noti -o`

#### Steps to reproduce
`NOTI_PUSHOVER_TOK='foo';noti -o`
`NOTI_PUSHOVER_TOK=foo;noti -o`

**Comment by variadico** [comment]
Ah, this is because you have the syntax wrong. The [wiki](https://github.com/variadico/noti/wiki) has the correct syntax documented.

```
# Wrong.
NOTI_PUSHOVER_TOK=foo; noti -o

# Right (no semi-colon)
NOTI_PUSHOVER_TOK=foo NOTI_PUSHOVER_DEST=bar noti -o
```
