### ISSUE TITLE
Allow custom sound effects

### ISSUE THREAD

**Issue by variadico** [variadico/noti#27]
> Would it be possible/easy to allow for the use of Custom sound effects if they are proprely configured in the OS? Even if this means I need to modify my local noti instance.

From #25

**Comment by variadico** [comment]
> Would it be possible/easy to allow for the use of Custom sound effects…

Not easy because Apple doesn't allow you to modify /System/Library/Sounds anymore.
https://support.apple.com/en-us/HT204899

**Comment by variadico** [comment]
Wait. You can already do this. Just put your custom `.aiff` sound file in `~/Library/Sounds`. Then you can do this: `NOTI_SOUND=mysound noti`

I should document this in the wiki.

**Comment by KingKrimmson** [comment]
Hmmm... I made the custom sound file (as you can see), and even tried to set that in my aliases profile, but it just reverted to the default sound. Perhaps this is a personal environment issue related to my Pushover issue. Will test further, thank you =)

**Comment by KingKrimmson** [comment]
Ahhh, yes. Seems to be entirely my own fault =P Was not properly exporting variables in my rc profile and, therefore, was getting those errors.

This is, in fact, functional as desired! Thank you!

**Comment by variadico** [comment]
w00t. :tada:
