### ISSUE TITLE
which OS are supported?

### ISSUE THREAD

**Issue by Pomax** [variadico/noti#28]
The README.md does not mention which operating systems are supported by this package - the screenshot and "OSX" section suggest it's OSX only, but can that information be explicitly added to prevent people from getting their hopes up? (or, if everything supports it, yay! That's good to mention)

**Comment by variadico** [comment]
`noti` should run on any platforms where you can run Go programs. See https://golang.org/dl for a list.

However, there are certain features that only work on OS X, like `NSUserNotification`s. There are other features that only work on Linux and FreeBSD, like eSpeak. Hypothetically, the web notifiers, e.g. Slack, Pushbullet, should be able to run on all platforms, though I haven't actually tested them outside of OS X and Linux.

Features that are platform-specific are conditionally compiled, including the documentation, so doing a
```
go get -u github.com/variadico/noti
```
should get you a version of `noti` tailored for your specific OS. Anything that appears in `noti-h` on your OS should work.

**Comment by Pomax** [comment]
Nice! Can he fact that it runs on all OS be added to the README then? (some other notification libs, even when written in a supposedly universal language, rely on specific OS libraries that make them not work on OSX, or Windows, or plain 'n'x, etc)

**Comment by variadico** [comment]
Closing. This is now in master.

**Comment by Pomax** [comment]
nice, thanks!
