### ISSUE TITLE
Support for Linux?

### ISSUE THREAD

**Issue by thewhitetulip** [variadico/noti#3]
Linux uses a notify-send tool to send similar kind of notifications, I'd love to send a PR, will you be open to merge it?

**Comment by cryptix** [comment]
I also planned on opening a PR for this but time is already slipping again, this week. Feel free to take inspiration from [tnse](https://github.com/cryptix/cmd/tree/master/tnse) for this.

**Comment by variadico** [comment]
That would be awesome. I thought about Linux support, but just never got around to it. A PR would be appreciated. :)

**Comment by thewhitetulip** [comment]
Cheers :+1:
