### ISSUE TITLE
Notifications for aliased commands

### ISSUE THREAD

**Issue by chmaynard** [variadico/noti#30]
#### Description

I would like to use noti to execute aliased commands. For example, I frequently use this alias:
```
alias hb='brew update; brew upgrade; brew cleanup'
```
When I tried running ```noti hb```, I got this notification:

<img width="298" alt="screen shot 2016-07-15 at 5 39 30 pm" src="https://cloud.githubusercontent.com/assets/13698964/16889280/3d8d932a-4ab3-11e6-8298-9fe4191ada7f.png">

**Comment by variadico** [comment]
This was previously discussed here: https://github.com/variadico/noti/issues/11

**Comment by chmaynard** [comment]
Agreed.
