### ISSUE TITLE
problem in sending  to pushover 

### ISSUE THREAD

**Issue by muralikodali** [variadico/noti#34]
NOTI_PUSHOVER_TOKEN=foo  NOTI_PUSHOVER_DEST=bar noti -o
producing the result : **Pushover API: application token is invalid**

**Comment by variadico** [comment]
Is the API token valid?

**Comment by muralikodali** [comment]
yes, it is valid api token.

-- 
Regards,
Murali Kodali

**Comment by trizko** [comment]
The README.md says the environment variable is supposed to be `NOTI_PUSHOVER_TOK` not `NOTI_PUSHOVER_TOKEN`.

**Comment by muralikodali** [comment]
sorry for typo in email.but actual command  is given with  NOTI_PUSHOVER_TOK.
when variables are given in zshrc, output is **invalid configuration for NOTI_PUSHOVER_TOK: missing**

**Comment by variadico** [comment]
Are you sure you set everything up correctly? I just tried the Pushover notifications and it worked for me.

```
cmd/noti (dev) > export NOTI_PUSHOVER_DEST="my User Key"
cmd/noti (dev) > export NOTI_PUSHOVER_TOK="my API Token/Key"
cmd/noti (dev) > noti -o
cmd/noti (dev) > 
```

I successfully received the Pushover notification on my Nexus 5X.

Maybe this can help?
https://github.com/variadico/noti/blob/dev/docs/noti.md#using-pushover

**Comment by muralikodali** [comment]
sorry  for the inconvience.
As there is no configuration file, i have tested on terminal with command:
$**export NOTI_PUSHOVER_DEST="foo"  NOTI_PUSHOVER_TOK="bar";noti -o** with output **Pushover API: application token is invalid**.
terminal command should be: **export NOTI_PUSHOVER_DEST="foo" ;export  NOTI_PUSHOVER_TOK="bar";noti -o**

**Comment by variadico** [comment]
Sweet. Closing. 👍
