### ISSUE TITLE
Bash profiles

### ISSUE THREAD

**Issue by vyasgiridhar** [variadico/noti#40]
Is there a way to load bash profiles and execute it as a bash command?

**Comment by variadico** [comment]
Maybe. Sorry, I'm not entirely sure what you mean.
What use case are you trying to solve? Or what kind of workflow are you envisioning?

**Comment by vyasgiridhar** [comment]
I have a ton of aliases in my bash profile.

**Comment by vyasgiridhar** [comment]
Exactly. 

It is possible.

**Comment by variadico** [comment]
> It is possible.

Awesome! How? 

I'm open to adding this, just don't know of a way to do it without using regexp to parse `.bash_profile` or something like that.

**Comment by vyasgiridhar** [comment]
But bash doesn't allow you to run a command after sourcing the rc file. 

The only way to do it would be to parse .bashrc and .bash_profile like you said.

**Comment by variadico** [comment]
Ooh. I imagine this is kinda tricky. What are all of the possible files that users can define aliases?

* $HOME/.bashrc
* $HOME/.bash_profile
* $HOME/.profile
* $HOME/.bash_aliases
* /etc/profile
* /etc/bash.bashrc
* Probably more?

And that's just for bash. What about other shells, like ZSH?

**Comment by vyasgiridhar** [comment]
Well in bash, the files are 
```
/etc/profile
/etc/bash.bashrc 
~/.bashrc  
~/.bash_profile
~/.bash_login 
~/.profile  
```

And in zsh the files are : 
```
/etc/zshenv
~/.zshenv
/etc/zprofile
~/.zprofile 
/etc/zshrc
~/.zshrc
/etc/zlogin
~/.zlogin

```

What other files do we need to look into?

**Comment by variadico** [comment]
Okay. Definitely interested in fixing this issue, but I'm going to close this issue so we can continue the conversation on the original issue.

Let's move here: https://github.com/variadico/noti/issues/11
