### ISSUE TITLE
Feature request: send notifications to Mattermost

### ISSUE THREAD

**Issue by AlekSi** [variadico/noti#41]
https://www.mattermost.org

**Comment by pascalandy** [comment]
Glad to find this here:)

+1

**Comment by c-f** [comment]
I'm currently developing this feature for Mattermost. However it is still possible to send notification, using **Bearychat** as a workaround.

Example using bearychat (**-c**) with an Mattermost url: 
```
# Using Bearychat to send messages to mattermost
export NOTI_BEARYCHAT_INCOMINGHOOKURI=https://<mattermost-host>/hooks/<webhook>; 
noti -c -t "title" -m "message"
```
Noti will still display a warning (based on Mattermost "ok"  as the response body ), but  the message is still delivered correctly to Mattermost and noti will quit with a normal exit status (0). 
```
# Warning Output of the Bearychat bypass
2018/05/02 12:44:50 decoding response: invalid character 'o' looking for beginning of value
```

**Comment by variadico** [comment]
Coming soon.
