### ISSUE TITLE
Feature request: read message from stdin.

### ISSUE THREAD

**Issue by AlekSi** [variadico/noti#44]
It would be helpful to allow `noti` to read notification message from stdin. For example, running `make | noti -m=-` will send a notification with the last line of stdin.

**Comment by variadico** [comment]
I'm not opposed to this change, but what use case would this solve? I'd like to get a better idea of how other people use `noti`. :)

**Comment by variadico** [comment]
Resolved by https://github.com/variadico/noti/pull/112
