### ISSUE TITLE
OS X: Banners vs Alerts

### ISSUE THREAD

**Issue by notDavid** [variadico/noti#50]
Currently noti displays Banners. Banners go away automatically after a few seconds so you might easily miss them.
Would it be possible to trigger Alerts also - when passing in some option like 'noti -a echo hello' or whatever?
Or is this already possible somehow?

fyi, for regular apps you can specify this on a per App basis in "System preferences -> Notifications":

![i](https://gist.githubusercontent.com/notDavid/c39e3543917ed0ee30edff195b355bf0/raw/b348ade819512092571380d2c3c0ab93155865fb/notifications.png)

#### Version
$ go version
go version go1.7.1 darwin/amd64

$ noti -version
noti v2.3.0
latest: v2.3.0

**Comment by KingKrimmson** [comment]
Currently, you can enable this by setting the alert style for Terminal

**Comment by variadico** [comment]
Sweet. Thanks for the assist, @KingKrimmson.

Also, note that clicking on the "Show" button doesn't work right. This is related to #15. :(

**Comment by notDavid** [comment]
@KingKrimmson

Thanks. Because i use iTerm2 i tried setting the alert style for that app. I didn't expect setting the alert style for Terminal would have any effect :)

By the way, it would be nice to be able to specify this alert style per command by some commandline option... but i don't know if the author can/wants to implement that.
