### ISSUE TITLE
Update go-toast

### ISSUE THREAD

**Issue by jacobmarshall** [variadico/noti#52]
Hey, just wanted to let you know that a new version of [`toast`](https://github.com/go-toast/toast) (formerly go-toast) is available, which makes it possible for users with a freshly installed version of Windows 10 to use toast notifications. Previously they would have to change their PowerShell execution policy globally, now none of that is necessary.

Also, just wanted to point out that the repo has moved to `go-toast/toast` so it can be more easily used with gopkg.in. And one other thing to note is that in the move to v1, I added audio & duration support (etc...), however you now need to specify a sound, or the toast will be silent. Just thought I'd mention that :)

Thanks again for using `toast` :)

**Comment by jacobmarshall** [comment]
Just wanted to note that the default sound issue has been resolved 😜

**Comment by variadico** [comment]
This is in master now.
