### ISSUE TITLE
Nomenclature to use noti with Slack

### ISSUE THREAD

**Issue by pascalandy** [variadico/noti#55]
#### Description
Trying to use **noti** with slack and it looks I don't get the right nomenclature at this point. 
I want to put this within a fonction that will be called by a cron. 

What's wrong here?

Cheers!
Pascal

#### Steps to reproduce
```
echo "test slack" \ 
noti -k -m "The task XYZ is done - $(date +%Y-%m-%d_%Hh%M_%S)" \
-e NOTI_SLACK_TOK="sometokenq53yq3-5y-q35yq345yq45y-aergaergaergaergaerg" \
-e NOTI_SLACK_DEST="#cron"
```

#### Version
go version go1.7.4 linux/amd64
noti v2.5.0

**Comment by variadico** [comment]
Where is the `-e` flag coming from? I didn't see it in `noti -h`. Maybe try:

```
NOTI_SLACK_TOK="sometokenq53yq3-5y-q35yq345yq45y-aergaergaergaergaerg" \
NOTI_SLACK_DEST="#cron" \
noti -k -m "The task XYZ is done - $(date +%Y-%m-%d_%Hh%M_%S)"
```

**Comment by pascalandy** [comment]
Great, it's working perfectly now :)
Here is how I wrapped it. Feel free to put this in your example section :)

```
SLACK_TOKEN="kfLZU0iaPOUW +27Dp7LH3f xJM65xwUA5Xla8 Zqu5408Z3 Qp2tkAJg u7ACXkVZz"
SLACK_CHANNEL="#cron"
ENV_NOW=$(date +%Y-%m-%d_%Hh%M_%S)
NOTI_MESSAGE="The task XYZ is done - $ENV_NOW"

NOTI_SLACK_TOK="$SLACK_TOKEN" NOTI_SLACK_DEST="$SLACK_CHANNEL" noti -k -m "$NOTI_MESSAGE"
```

**Comment by variadico** [comment]
👍
