### ISSUE TITLE
How to rename the default bot name `noti`

### ISSUE THREAD

**Issue by pascalandy** [variadico/noti#57]
#### Use case
In slack the default bot name is `noti`.
Can you tell where I could rename this to another friendly name like `Pikwi`

Here is how my setup looks like :)
<img width="1381" alt="screen shot 2016-12-09 at 2 50 06 pm" src="https://cloud.githubusercontent.com/assets/6694151/21062536/64f0c4b6-be1f-11e6-8726-81afc8537801.png">

Cheers!
Pascal

#### Version
go version go1.7.4 linux/amd64
noti v2.5.0

**Comment by variadico** [comment]
Fixed by: https://github.com/variadico/noti/pull/68
