### ISSUE TITLE
Benefit over notify-send or terminal-notifier?

### ISSUE THREAD

**Issue by eosrei** [variadico/noti#7]
I can already what this project does (I think!) via `notify-send` in Linux and OS X via https://github.com/julienXX/terminal-notifier What is the benefit vs those? Could you make the benefits more clear in the readme? Thanks!

**Comment by variadico** [comment]
Hi, there. I have never actually used terminal-notifier before, but I have used notify-send before. Here are some notes I took on my bus ride home.

**Similarities with terminal-notifier**
* Both use NSUserNotification¹ to show notifications on OS X.
* Both can be used from the terminal.
* Both can be used as a library².

**Similarities with notify-send**
* Both use libnotify³ to show notifications on Linux and FreeBSD.
* Both can be used from the terminal.

**Differences**
* Noti has a shorter name. Just 4 tiny letters (`noti`) vs 17 bajillion letters (`terminal-notifier`) vs 11 gazillion letters (`notify-send`).
* Noti has shorter syntax. At minimum, Noti takes 0 arguments, whereas terminal-notifier 1 and notify-send 2. Noti has short and long flags, whereas terminal-notifier only has long flags.
* Noti is written in Go, not Ruby.
* Noti binaries are statically linked and don't require Go to execute.
* Noti doesn't come in a .app bundle.
* Noti works on OS X, Linux, and FreeBSD, whereas terminal-notifier only on OS X and notify-send only on Linux and FreeBSD.
* Noti has more than just desktop notifications, including smartphone and speech⁴ notifications—which you can pick by passing a flag.

That's just off the top of my head. If you're curious about where Noti is headed, you can [checkout the v2 branch](https://github.com/variadico/noti/tree/v2). I'm still working out the design, so things could change overnight, but that's basically the direction I'll be going.

¹ In v1.3.0, Noti uses AppleScript to trigger a notification. In v2, Noti will use Objective-C directly instead.
² In v2, Noti will contain different notification packages that can be used as a library.
³ In v1.3.0, Noti calls `notify-send` to trigger a notification. In v2 Noti will use `libnotify` directly instead.
⁴ Coming in v2. Speech notifications will be OS X only in the beginning.

**Comment by eosrei** [comment]
I've only used `notify-send` myself, so that's why I was wondering if there would be a benefit to switching. `notify-send` is part of Gnome's codebase for `libnotify` so it's on my computer either way. Note: It's in C, not Ruby https://git.gnome.org/browse/libnotify/tree/tools/notify-send.c (You were probably referring to terminal-notifier though?) and it does work with one argument.

I'll enjoy being able to get additional notification types in the future with v2. Thank you for the detailed comparison!

Should I close or do you want to leave open for the readme?

**Comment by variadico** [comment]
> It's in C, not Ruby

Yeah, I was talking about terminal-notifier.

> it does work with one argument

Oh, neat! My bad.

I might think about this later for the readme. I'll close it for now. Good night!
