### ISSUE TITLE
tag does not include `v` in the name this time

### ISSUE THREAD

**Issue by ilovezfs** [variadico/noti#71]
I'm not sure if this was intentional but https://github.com/variadico/noti/tags shows all previous tags had a prepended `v` and 3.0.0 does not.

**Comment by y0ssar1an** [comment]
IMHO we should all stop prepending our git tags with `v` for the simple reason that `v1.2.3` is not valid SemVer. As long as we `prepend` with `v`, we have to do a little extra work to translate git tags into versions, e.g. [`git describe --tags --abbrev=0 | tr -d 'v'`](https://github.com/variadico/noti/blob/master/Makefile#L2). A `git` tag shouldn't have to be _translated into_ a version. A `git` tag should _be_ the version.

**Comment by ilovezfs** [comment]
On the flip side, the GitHub GUI (Click `Draft a new release` suggests tags with `v`)

>Tagging suggestions
>
>It’s common practice to prefix your version names with the letter v. Some good tag names might be v1.0 or v2.3.4.
>
>If the tag isn’t meant for production use, add a pre-release version after the version name. Some good pre-release versions might be v0.2-alpha or v5.9-beta.3. 

So good luck getting it to stop :)

**Comment by ilovezfs** [comment]
https://stackoverflow.com/questions/28605883/why-do-so-many-projects-prepend-v-to-the-git-version-tags

>is not valid SemVer

I think it still is. It used to be required apparently.

**Comment by ilovezfs** [comment]
@y0ssar1an fyi: https://github.com/semver/semver/blob/master/semver.md#is-v123-a-semantic-version

**Comment by y0ssar1an** [comment]
Thanks for prompting me to research this further. Apparently, prepending the `v` was [_required_ in SemVer 1.0.0](https://semver.org/spec/v1.0.0.html#spec-item-1), but is [invalid in SemVer 2.0.0](https://github.com/semver/semver/blob/master/semver.md#is-v123-a-semantic-version). As you mentioned, the `v` is some historical cruft coming from pre-`git` version control systems.

**Comment by variadico** [comment]
The [changelog](https://github.com/variadico/noti/blob/master/docs/CHANGELOG.md) has always said that this project uses semver. It seems silly to say that, but not actually follow semver. It also makes it easier to parse the version from the tag, which [noti does](https://github.com/variadico/noti/blob/master/Makefile#L2).

So in short, yup, this was on purpose! 😄 Thanks for double checking!

**Comment by ilovezfs** [comment]
@variadico thanks for clarifying that! For the record, current semver itself says in https://github.com/semver/semver/blob/master/semver.md#is-v123-a-semantic-version

>Example: `git tag v1.2.3 -m "Release version 1.2.3"`, in which case "v1.2.3" is a tag name and the semantic version is "1.2.3".

So there is nothing contradictory about having a `v` in the tag name because semver allows for a distinction between the "tag name" and the "semver version" itself.
