### ISSUE TITLE
Message setting doesn't work

### ISSUE THREAD

**Issue by kamikai** [variadico/noti#72]
#### Description
The `--message` / `-m` flag is not correctly setting the message field of notifications. No matter what is specified, the message field is always the string "Done!".

#### Steps to reproduce
``` bash
noti -t "My Title" -m "My Message"
```

This behaviour occurs when the configuration file is missing. An empty file resolves it, as [pointed out](https://github.com/variadico/noti/issues/72#issuecomment-369241195) by @heidark.

#### Expected behavior
The message field of notification popups / voice readouts to be "My Message".

#### Actual behavior
The message fields remains the default string "Done!".
<img width="381" alt="screen shot 2018-01-24 at 4 17 07 pm" src="https://user-images.githubusercontent.com/4208581/35317564-1737c650-0123-11e8-9834-c762f0b7c96b.png">

#### Version
`3.0.0`, installed via Homebrew on MacOs 10.13.2

<img width="446" alt="screen shot 2018-01-24 at 4 17 13 pm" src="https://user-images.githubusercontent.com/4208581/35317546-f789f1fc-0122-11e8-8a1b-64ca88e015de.png">

**Comment by variadico** [comment]
Hm, strange. I can't seem to repro. Can you share the output of this command?

```
noti --verbose -t "My Title" -m "My Message"
```

**Comment by kamikai** [comment]
Sure Thing:
```
$ noti --verbose -t "My Title" -m "My Message"
Failed to configure: failed to read config file: [open .noti.yaml: no such file or directory open /Users/tkc/.config/noti/noti.yaml: no such file or directory]
title: My Title
Running command: []
Services: map[banner:{}]
Viper: map[title:My Title say:map[voice:Alex] pushbullet:map[accesstoken:] bearychat:map[incominghookuri:] message:Done! simplepush:map[key: event:] slack:map[channel: username:noti token:] hipchat:map[room: accesstoken:] defaults:[banner] espeak:map[voicename:english-us] pushover:map[apitoken: userkey:] nsuser:map[soundnamefail:Basso soundname:Ping] pushsafer:map[key:] speechsynthesizer:map[voice:Microsoft David Desktop]]
1 notifications queued
Sent: *nsuser.Notification
```

**Comment by heidark** [comment]
If there is no .noti.yaml in the folder you are in when you run noti, it ignores the message flag.

creating a empty .noti.yaml file fixes the problem but only for that given directory.

the issue might here:
https://github.com/variadico/noti/blob/960a214d7f2b2ef4866ac8f90048b65032c7c9bf/internal/command/config.go#L182-L192

**Comment by kamikai** [comment]
Creating an empty file `~/.config/noti/noti.yaml` worked, thank you kindly @heidark.

**Comment by variadico** [comment]
Ooooh, nice! I can definitely reproduce this now! Thanks @heidark! Patch release will be coming soon!

**Comment by variadico** [comment]
Thanks everyone!
I believe this should be fixed on latest [dev](https://github.com/variadico/noti/commit/a218664e8987e7c750b493cd9626cccc3daf6744).

Closing now. Patch release will be coming soon!
