### ISSUE TITLE
Bug in release description

### ISSUE THREAD

**Issue by AlekSi** [variadico/noti#77]
https://github.com/variadico/noti/releases/tag/3.0.0 says:
```
| Deprecated           | Current                        |
---------------------------------------------------------
| NOTI_PUSHOVER_TOK    | NOTI_PUSHOVER_TOKEN            |
| NOTI_PUSHOVER_DEST   | NOTI_PUSHOVER_USER             |
```

But docs (https://github.com/variadico/noti/blob/master/docs/noti.md#environment) call them `NOTI_PUSHOVER_APITOKEN` and `NOTI_PUSHOVER_USERKEY`.

**Comment by variadico** [comment]
Yup! This was recently fixed.
https://github.com/variadico/noti/pull/76

**Comment by variadico** [comment]
Closing since this is now in `dev`.
