### ISSUE TITLE
Telegram support

### ISSUE THREAD

**Issue by subvillion** [variadico/noti#86]
Omit non-relevant sections.

#### Description
Please add support send message to Telegram https://core.telegram.org/bots/api#sendmessage

simple curl ex:
```curl -s -X POST https://api.telegram.org/bot<TOKEN>/sendMessage -d chat_id=<CHAT_ID> -d text="Hello World"```

**Comment by pascalandy** [comment]
I would this as well

**Comment by Altenrion** [comment]
this will covet all other "push" services

**Comment by mark05e** [comment]
+1

**Comment by phillipahereza** [comment]
What's the status on this? Has it greenlit for implementation or are they any other concerns. If this ok to add, I'd like to work on it

**Comment by variadico** [comment]
@phillipahereza, sounds good. Go for it! :+1:

**Comment by variadico** [comment]
Thanks @phillipahereza 
https://github.com/variadico/noti/pull/102
Closing.
