### ISSUE TITLE
The freedesktop notification disappears too quickly

### ISSUE THREAD

**Issue by epitron** [variadico/noti#88]
#### Version
3.1.0

#### Description
The ExpireTimeout for freedesktop notifications is currently set to 0.5 seconds, which is much too fast (especially if you're working on something else!)

The default timeout on XFCE's notifyd is 10 seconds, which is more comfortable.

`noti` currently has no way to configure this, so a better default would be to let the notification daemon decide what the timeout should be. If you think users might need more control, maybe a config option?

**Comment by teto** [comment]
I have the same problem. Seems like a fix is available at https://github.com/variadico/noti/pull/82

**Comment by variadico** [comment]
https://github.com/variadico/noti/pull/82 merged. Closing this issue.

**Comment by teto** [comment]
thanks
