### ISSUE TITLE
Allow for installation through homebrew

### ISSUE THREAD

**Issue by jakehschwartz** [variadico/noti#9]

**Comment by fabiantheblind** [comment]
+1

**Comment by nunoh** [comment]
Yep this would be rather nice

**Comment by mgbellaire** [comment]
+1

**Comment by flexzuu** [comment]
+1

**Comment by derekperkins** [comment]
:+1:

**Comment by mmizutani** [comment]
Hi guys, wait a while for [my pull request of the reti recipe](https://github.com/Homebrew/homebrew/pull/48163) to be merged to the Homebrew repository.

**Comment by wayferer** [comment]
````
brew update
brew install noti
````

:+1:

**Comment by nunoh** [comment]
so nice. thanks @mmizutani

**Comment by mmizutani** [comment]
From now on you can install noti through Homebrew (but not yet through Linuxbrew):

```sh
$ brew update
$ brew install noti
$ noti 
```

If you want to thank @variadico using the pre-release or dev branch head version:

```sh
$ brew update
$ brew install noti --devel # 2.0.0-rc.1
$ brew install noti --HEAD # https://github.com/variadico/noti/tree/dev
$ noti -V 'Agnes' -t '' -m 'variadico, thank you for creating noti.'
```

**Comment by variadico** [comment]
Whoa, you guys are awesome!

Work has been keeping me busy, but **thank you** so much for jumping in and resolving this, @mmizutani! :beers: :gift:
