### ISSUE TITLE
noti launches a login shell when trying to run a shell function or alias

### ISSUE THREAD

**Issue by gimbo** [variadico/noti#90]
#### Description

It seems that when `noti` runs a user-defined shell function or alias, it launches a login shell; that can cause unwanted output which we wouldn't ordinarily expect to see. I _think_ the right thing to do is to launch a non-login shell, which (assuming the user has their shell initialisation files set up properly) should set up functions, aliases, environment, etc. without producing any output.

I noticed this behaviour in `zsh` and have only investigated/described it there; looking briefly at the `noti` source [it seems to be using a generic mechanism for launching subshells](https://github.com/variadico/noti/blob/master/internal/command/root.go#L199) so I expect this would affect `bash`, etc. too.

It seems to me that removing the `"-l"` parameter from `args` in `subshellCommand()` would do it; was there a particular reason for including it in the first place? (I'm not a go programmer however, so I'm not set up for just trying out removing this myself - apologies.)

#### Use case

Use case is using `noti` with user-defined shell functions or aliases.

#### Steps to reproduce

* Define a shell function or an alias in `~/.zshrc`
* Put some output-producing code in `~/.zlogin`
* Call the shell function or alias under `noti`
* Unexpected behaviour: output-producing code in `~/.zlogin` is run.

Example:

```
$ cat ~/.zshrc
echo "This is .zshrc"

foo() {
  echo 'This is foo'
}
alias bar="echo 'This is bar'"

$ cat ~/.zlogin
echo "This is .zlogin"

$ foo
This is foo

$ bar
This is bar

$ noti foo
This is .zshrc
This is .zlogin
This is foo

$ noti bar
This is .zshrc
This is .zlogin
This is bar
```

#### Expected behavior

I would expect the code in `~/.zlogin` not to run, so I'd expect not to see the text `This is '.zlogin'` above.

#### Actual behavior

See above. :-)

#### Version

```
$ go version
go version go1.10.3 darwin/amd64

$ noti --version
noti version
Latest: 3.1.0
Download: https://github.com/variadico/noti/releases/tag/3.1.0
```

**Comment by variadico** [comment]
Fixed by https://github.com/variadico/noti/commit/16943d4f51d3c2609723193df8b319f3031b94be.

I use bash and seems like removing `-l` doesn't cause any problems. So let's take it out.

Looking more closely at:

```
$ cat ~/.zshrc
echo "This is .zshrc"

foo() {
  echo 'This is foo'
}
alias bar="echo 'This is bar'"
```

Seems like it might not be possible to suppress this echo statement. We need to run `~/.zshrc` in order to get access to the function and alias.
