### ISSUE TITLE
brew formula missing man pages/docs

### ISSUE THREAD

**Issue by ventz** [variadico/noti#92]
#### Description
It seems that the homebrew (`brew`) formula of noti is missing the man pages/any docs
Assuming you maintain it?

```
% brew info noti
noti: stable 3.1.0 (bottled)
Trigger notifications when a process completes
https://github.com/variadico/noti
/usr/local/Cellar/noti/3.1.0 (3 files, 12.8MB) *
  Poured from bottle on 2018-11-14 at 12:42:32
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/noti.rb
==> Dependencies
Build: go ✔
```

#### Use case
Documentation about the needed tokens for services like pushbullet/pushover/slack/etc.

#### Steps to reproduce
`brew install noti`

#### Expected behavior
`man` pages to be installed :)

#### Actual behavior
`man` pages are *not* installed

#### Version
* go version: go1.11.2 (latest in brew as of 11/14/18)
* noti version: 3.1.0 (latest in brew as of 11/14/18)

**Comment by variadico** [comment]
Does anyone know how to fix this? I'm actually 100% on Linux these days and don't own a Mac. :grimacing:

**Comment by dawidd6** [comment]
> Does anyone know how to fix this? I'm actually 100% on Linux these days and don't own a Mac.

https://docs.brew.sh/Homebrew-on-Linux

**Comment by dawidd6** [comment]
It should be resolved now.

**Comment by ventz** [comment]
Thanks!

**Comment by variadico** [comment]
Sweet, thanks!
