### ISSUE TITLE
Errors on headless installation.

### ISSUE THREAD

**Issue by jottr** [variadico/noti#96]
`noti` doesn't work well on headless installations, since it requires the following packages to be installed. 
Example on ubuntu 18.10: 

```
$ ./noti
2019/03/09 16:00:17 dbus connect: exec: "dbus-launch": executable file not found in $PATH

# Fix for dbus-error 
sudo apt install dbus-x11

# But then:
$ ./noti
2019/03/09 16:01:54 notify: The name org.freedesktop.Notifications was not provided by any .service files
```
Sadly, this makes `noti` useless on a server installation.  
Being able to send a pushbullet notification when a long running process finishes on a server would be a prime example of a great use case for `noti`.   

Related [issue](https://github.com/variadico/noti/issues/83), which was closed without comments.

**Comment by variadico** [comment]
Sorry for the late response!

Try passing `--verbose`. I think this is happening because `noti` is trying to send a desktop notification in your server, which you can't because you don't have a desktop environment. Verbose should confirm this.

If this is the case, then try passing `-b = false` to turn off the desktop banner notification.

There should be a better error message here.

**Comment by variadico** [comment]
Closing this for now because I think this is resolved. I tried running in a Docker container, got the error message you posted, but then noti worked when I disabled the banner notification.

**Comment by jottr** [comment]
Using `-b false` seems to not resolve the issue: 

```
$ ./noti -b  false --verbose
2019/06/30 17:30:24 notify: The name org.freedesktop.Notifications was not provided by any .service files
```

**Comment by variadico** [comment]
Can you post `noti --version`? Also, maybe try `-b=0 --verbose` just in case.

**Comment by jottr** [comment]
```
$ ./noti --version 
noti version 3.2.0
```

Using `-b=0` fixed it. Maybe this can be added to the documentation?

**Comment by variadico** [comment]
Yep, yep. Good idea. I'll add it to the docs. Thanks for helping debug this! :+1:
